### ISSUE TITLE
Allow bringing own Private DNS zone

### ISSUE THREAD

**Issue by Jorrit05** [CloudNationHQ/terraform-azure-aks#29]
When deploying enterprise-scale I usually let it create all PrivateLink DNS zones, for AKS that is:
- privatelink.westeurope.azmk8s.io

In the current module, when creating a Private AKS cluster, the variable 'private_dns_zone_id' is missing. It would be good to add this, otherwise AKS will create its own Private DNS zone, which you then need to remember to link to a  (hub) Virtual network for name resolution. 

This requires a bit of research because the AKS cluster needs the 'DNS zone contributor' role to make entries in that Zone.

**Comment by MDBeudekerCN** [comment]
+1

**Comment by dkooll** [comment]
This is already implemented. Closing the issue.
