### ISSUE TITLE
Starting from AKS 1.28 max_surge is set to 10%

### ISSUE THREAD

**Issue by cveld** [CloudNationHQ/terraform-azure-aks#51]
As per https://github.com/hashicorp/terraform-provider-azurerm/issues/24020 since AKS 1.28 max_surge is set to 10% for the default node pool by default.

Currently the module always reports a change on the max_surge setting from 10% to NULL when left to the defaults.

Desired situation:
The module should default to max_surge 10%.

Considerations:
AKS 1.27 is an LTS version. For customers running the defaults they will see a one time max_surge change from NULL to 10%. This seems a reasonable change as in line with the general kubernetes guidance.

Potentially this could be fixed in a future version of the azurerm provider as well which renders this request for a module patch unnecessary.

**Comment by dkooll** [comment]
This is a upstream issue. Decided to close this one.
