### ISSUE TITLE
[BUG] - os_type expects Linux or Windows, got linux

### ISSUE THREAD

**Issue by tovstcn** [CloudNationHQ/terraform-azure-aks#91]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Module Version

2.0.0

### Terraform Version

3.112.0

### AzureRM Provider Version

4.3.0

### Short Description

resource "azurerm_kubernetes_cluster_node_pool " expects argument os_type expects linux with capital L

### Terraform Configuration Files

```
module "aks_rbac" {
  source  = "cloudnationhq/aks/azure"
  version = "~> 2.0"

  keyvault = data.azurerm_key_vault.kv.id #use existing kv from baseline

  cluster = {
    resource_group = module.rg.groups.assai.name
    location       = module.rg.groups.assai.location

    node_pools = var.rbac_limited_node_pool ? {} : {
      for pool_name, pool_config in var.aks.node_pools :
      pool_name => {
        name                    = try(pool_config.name, pool_name)
        vm_size                 = try(pool_config.vmsize, "Standard_D4as_v5")
        node_count              = try(pool_config.rbac_node_count, pool_config.node_count, null)
        max_surge               = try(pool_config.max_surge, 50)
        max_count               = try(pool_config.max_count, null)
        max_pods                = try(pool_config.max_pods, 30)
        min_count               = try(pool_config.min_count, null)
        os_disk_type            = try(pool_config.os_disk_type, null)
        enable_auto_scaling     = try(pool_config.auto_scaling, false)
        zones                   = try(pool_config.availability_zones, [1, 2, 3])
        vnet_subnet_id          = data.azurerm_subnet.aks.id
        custom_ca_trust_enabled = false
        os_type                 = "Linux"
      }
    }
```

### Expected Behaviour

Expected module to process the dynamic blocks depending on os_type such as "linux_os_config" and "kubelet_config" but they do not get passed because the condition expects "linux" all without capitals. 

### Actual Behaviour

Does not pass arguments for "linux_os_config" and "kubelet_config" and therefore cannot process them with custom values. Please make it so that we can add it. possible fix is adding "Linux" within the condition instead of "linux"

### Steps to Reproduce

terraform apply

**Comment by dkooll** [comment]
solved in #96
